# -*- coding: utf-8 -*-
"""app.py - Herramienta de Análisis de Precios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPP79BQ6-f-pk24zMj8Z4JEOCsw1O2SQ
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import re
from datetime import datetime

# --- Configuración de la Página de Streamlit ---
st.set_page_config(
    layout="wide",
    page_title="Análisis de Precios SERP",
    page_icon="📈"
)

# --- Funciones de Procesamiento de Datos ---

@st.cache_data # Cache para mejorar el rendimiento. No se reprocesa si los archivos no cambian.
def load_and_process_data(uploaded_files):
    """
    Carga, une y limpia los datos de los archivos CSV subidos.
    Esta función está adaptada a la estructura de tus archivos.
    """
    if not uploaded_files:
        return pd.DataFrame(), pd.DataFrame()

    all_data = []
    for file in uploaded_files:
        try:
            df = pd.read_csv(file)
            # --- Procesamiento de Fecha ---
            # Convierte la columna 'fecha' (formato DDMMAA) a un objeto de fecha real.
            # `errors='coerce'` convertirá fechas inválidas en NaT (Not a Time).
            df['fecha'] = pd.to_datetime(df['fecha'], format='%d%m%y', errors='coerce')
            all_data.append(df)
        except Exception as e:
            # Notifica al usuario si un archivo no se puede procesar.
            st.warning(f"No se pudo procesar el archivo {file.name}: {e}")
            continue

    if not all_data:
        return pd.DataFrame(), pd.DataFrame()

    # Unir todos los DataFrames de los archivos en uno solo.
    full_df = pd.concat(all_data, ignore_index=True)

    # --- Limpieza de Datos ---
    # Eliminar filas donde la fecha no se pudo convertir.
    full_df.dropna(subset=['fecha'], inplace=True)

    # Limpiar columna de precio (formato: $ 150.999,00)
    if 'precio' in full_df.columns:
        # 1. Convertir a string para asegurar que los métodos .str funcionen.
        # 2. Eliminar el símbolo '$' y los puntos de miles.
        # 3. Reemplazar la coma decimal por un punto.
        # 4. Convertir la columna a tipo numérico.
        # 5. `errors='coerce'` manejará cualquier valor que no se pueda convertir.
        price_series = full_df['precio'].astype(str)
        price_series = price_series.str.replace(r'[$.]', '', regex=True).str.replace(',', '.', regex=False)
        full_df['precio'] = pd.to_numeric(price_series, errors='coerce')

    # Limpiar dominio (aunque ya está limpio, es una buena práctica).
    if 'dominio' in full_df.columns:
         full_df['dominio'] = full_df['dominio'].astype(str).str.strip()

    # Eliminar filas donde el precio es nulo después de la limpieza.
    full_df.dropna(subset=['precio'], inplace=True)

    # --- Cálculo de Precios Mínimos ---
    # Para cada producto y fecha, encuentra el precio mínimo.
    # `transform('min')` crea una nueva columna con el precio mínimo para ese grupo.
    full_df['precio_minimo'] = full_df.groupby(['fecha', 'producto'])['precio'].transform('min')
    # Marca las filas que tienen el precio más bajo.
    full_df['es_precio_mas_bajo'] = full_df['precio'] == full_df['precio_minimo']

    return full_df


# --- Título y Descripción de la App ---
st.title("📈 Herramienta Interactiva de Análisis de Precios")
st.markdown("""
Sube los archivos CSV de tus relevos de precios para visualizar y analizar las tendencias del mercado.
Esta herramienta te permitirá:
- Rastrear la evolución de tus precios y los de la competencia.
- Identificar qué competidores tienen las estrategias de precios más agresivas.
- Filtrar los datos por producto, competidor, rango de fechas y nivel de precio.
""")

# --- Barra Lateral (Sidebar) para Controles y Filtros ---
with st.sidebar:
    st.header("⚙️ Filtros y Controles")
    uploaded_files = st.file_uploader(
        "1. Carga tus archivos CSV",
        type=['csv'],
        accept_multiple_files=True,
        help="Puedes seleccionar múltiples archivos de relevo. La app los combinará automáticamente."
    )

    if not uploaded_files:
        st.info("Por favor, sube al menos un archivo CSV para comenzar el análisis.")
        st.stop()

    # Cargar y procesar los datos usando la función cacheada.
    df = load_and_process_data(uploaded_files)

    if df.empty:
        st.error("No se pudieron cargar datos válidos de los archivos. Revisa el formato de los CSV.")
        st.stop()

    st.success(f"{len(df)} registros cargados de {len(uploaded_files)} archivos.")

    # --- Filtros Dinámicos ---
    # Los filtros se basan en los datos cargados.

    # 2. Filtro de Rango de Fechas
    min_date = df['fecha'].min().date()
    max_date = df['fecha'].max().date()

    selected_date_range = st.date_input(
        "2. Selecciona un Rango de Fechas",
        value=(min_date, max_date),
        min_value=min_date,
        max_value=max_date,
        help="Selecciona el período que quieres analizar."
    )

    # 3. Filtro de Productos
    all_products = sorted(df['producto'].unique())
    selected_products = st.multiselect(
        "3. Selecciona Productos",
        options=all_products,
        default=all_products, # Por defecto, todos seleccionados
        help="Elige los productos para incluir en el análisis."
    )

    # 4. Filtro de Competidores
    all_domains = sorted(df['dominio'].unique())
    selected_domains = st.multiselect(
        "4. Selecciona Competidores",
        options=all_domains,
        default=all_domains, # Por defecto, todos seleccionados
        help="Elige los dominios para incluir en los gráficos."
    )

    # 5. Filtro de Nivel de Precio
    all_price_levels = df['price_level'].unique()
    selected_price_levels = st.multiselect(
        "5. Filtra por Nivel de Precio",
        options=all_price_levels,
        default=all_price_levels, # Por defecto, todos seleccionados
    )

# --- Filtrado del DataFrame Principal ---
# Se aplican los filtros de la barra lateral al DataFrame.
# Asegurarse que el rango de fechas sea de dos valores.
if len(selected_date_range) == 2:
    start_date, end_date = selected_date_range
    filtered_df = df[
        (df['fecha'].dt.date >= start_date) &
        (df['fecha'].dt.date <= end_date) &
        (df['producto'].isin(selected_products)) &
        (df['dominio'].isin(selected_domains)) &
        (df['price_level'].isin(selected_price_levels))
    ]
else:
    # Si el usuario solo selecciona una fecha, se usa solo esa.
    filtered_df = df[df['fecha'].dt.date == selected_date_range[0]]


# --- Panel Principal de Visualizaciones ---
st.header("📊 Visualización de Datos")

if filtered_df.empty:
    st.warning("No hay datos para mostrar con los filtros seleccionados. Por favor, ajusta los filtros.")
else:
    # --- Gráfico 1: Evolución de Precios ---
    st.subheader("1. Evolución de Precios por Producto")

    # Si hay muchos productos, hacer un gráfico por cada uno es mejor.
    # Si hay pocos, se pueden poner en un solo gráfico.
    if len(selected_products) > 1:
        # Crea un gráfico separado (facet) para cada producto.
        fig_evolucion = px.line(
            filtered_df,
            x='fecha',
            y='precio',
            color='dominio',
            facet_row='producto', # Clave para separar por producto
            markers=True,
            title="Evolución de Precios a lo Largo del Tiempo (por Producto)"
        )
        fig_evolucion.update_layout(height=300 * len(selected_products)) # Ajustar altura
        fig_evolucion.update_yaxes(matches=None, title="Precio (AR$)") # Escalas Y independientes
    else:
        # Gráfico simple si solo se selecciona un producto.
        fig_evolucion = px.line(
            filtered_df,
            x='fecha',
            y='precio',
            color='dominio',
            markers=True,
            title=f"Evolución de Precios para: {selected_products[0]}" if selected_products else "Evolución de Precios"
        )
        fig_evolucion.update_yaxes(title="Precio (AR$)")

    st.plotly_chart(fig_evolucion, use_container_width=True)

    # --- Gráfico 2: Ranking de Competidores ---
    st.subheader("2. Ranking de Competidores con Precios Bajos")

    # Contar cuántas veces cada dominio tuvo el precio más bajo.
    lowest_price_counts = filtered_df[filtered_df['es_precio_mas_bajo']]['dominio'].value_counts().reset_index()
    lowest_price_counts.columns = ['dominio', 'cantidad_precios_bajos']

    fig_ranking = px.bar(
        lowest_price_counts,
        x='dominio',
        y='cantidad_precios_bajos',
        color='dominio',
        title="Frecuencia con la que un Competidor Ofrece el Precio Más Bajo",
        labels={'dominio':'Competidor', 'cantidad_precios_bajos':'Nº de Veces con Precio Más Bajo'}
    )
    st.plotly_chart(fig_ranking, use_container_width=True)

    # --- Gráfico 3: Comparativa en un Día Específico ---
    st.subheader("3. Comparativa de Precios en un Día Específico")

    # Permitir al usuario seleccionar una fecha y un producto para un análisis detallado.
    col1, col2 = st.columns(2)
    with col1:
        selected_date_for_bar = st.selectbox(
            "Selecciona una Fecha",
            sorted(filtered_df['fecha'].dt.date.unique(), reverse=True)
        )
    with col2:
        selected_product_for_bar = st.selectbox(
            "Selecciona un Producto",
            selected_products
        )

    snapshot_df = filtered_df[
        (filtered_df['fecha'].dt.date == selected_date_for_bar) &
        (filtered_df['producto'] == selected_product_for_bar)
    ].sort_values('precio')

    if not snapshot_df.empty:
        fig_snapshot = px.bar(
            snapshot_df,
            x='dominio',
            y='precio',
            color='dominio',
            title=f"Precios para '{selected_product_for_bar}' el {selected_date_for_bar}",
            labels={'dominio':'Competidor', 'precio':'Precio (AR$)'},
            text='precio' # Muestra el valor del precio en la barra
        )
        fig_snapshot.update_traces(texttemplate='$%{text:,.0f}', textposition='outside')
        st.plotly_chart(fig_snapshot, use_container_width=True)
    else:
        st.info(f"No hay datos para '{selected_product_for_bar}' en la fecha seleccionada.")


    # --- Expander para ver los datos crudos ---
    with st.expander("Ver tabla de datos filtrados"):
        st.dataframe(filtered_df.drop(columns=['precio_minimo', 'es_precio_mas_bajo']).style.format({'precio': "AR$ {:,.2f}"}))